import streamlit as st
import pandas as pd
import numpy as np

df = pd.read_csv("https://raw.githubusercontent.com/labeconometria/MLxE/main/proyectos2do/datasets3.csv")

st.title("Proyecto 6")
st.write(" En la presente pagina, a partir de un dataset dentro del que se determina la potabilidad del agua a partir de caracteristicas especificas como la cantidad de carbono organico o su condutividad, se realizan lo siguiente: ")
st.subheader("Exploracion inicial: ")
st.write("Para la exploración inicial obtenemos información acerca del dataset cargado. En este encontramos 3276 entradas y un total de 10 variables dentro de ella (columnas). Así mismo vemos que de las 10 columnas de datos; 1 es de typo int, 9 de tipo float.Adicionalmente se observa que existen datos nulos en las variables ph, Sulfate y Trihalomethanes.")
st.dataframe(df)
st.caption("Dataframe interactiva: presionando una vez sobre el nombre de las variables se puede ver si existen datos nulos; presionando dos veces sobre los datos los muestra con mayor exactitud")
st.table(df.describe())
st.caption("Tabla con las caracteristicas desciptivas de las diferentes variables")
st.subheader("Limpieza de datos:")
st.write("En primer lugar, estas estadisticas descriptivas son tomadas antes de la eliminación de valores nulos y de los outliers, observandose así que en las variables ph, Solids, sulfate, Conductivity, Organic_carbon, Turbidity y Photability se presenta un sego negativo ya que la mediana es menor que la media, mientras que en Hardnes, Chloramines y Trihalomethanes la media es menor que la mediana, por lo que se presenta un sesgo positivo. ")
st.write("Como observamos en la información del data existen datos nulos que es necesario corregir. Comprobamos así por el metodo isna la cantidad de estos datos y dentro de que variable se encuentra.")

st.table(df.isna().sum())
st.write("A través del método LinearRegresion corregimos la existencia de datos nulos dentro de las variables identificadas ph, Sulfate y Trihalomethanes.")

st.write("Para determinar outliers multivariados se calcula la distancia de mahalanobis, evaluandose los resultados obtenidos en una prueba chi cuadrado, quedandonos con los datos que obtuvieron un p valor mayor a 0.05 , los indexamos dentro del dataframe y eliminamos los datos nulos (datos con un p valor menor a 0.05)")

st.subheader("Transformacion de datos:")
st.code("""data = data.astype({"Potability":"category"})""", language="python")
st.subheader("categorizacion: ")
st.write("Para la categorización, dividimos las variables en 4 intervalos.")
st.code(""" data["Conductivity_2"] = pd.cut(data["Conductivity"],4) 
data["Chloramines_2"] = pd.cut(data["Chloramines"],4) 
data["Hardness_2"] = pd.cut(data["Hardness"],4) 
data["Solids_2"] = pd.cut(data["Solids"],4) 
data["Organic_carbon_2"] = pd.cut(data["Organic_carbon"],4) 
data["Turbidity_2"] = pd.cut(data["Turbidity"],4) 
data["ph_2"] = pd.cut(data["ph"],4) 
data["Sulfate_2"] = pd.cut(data["Sulfate"],4) 
data["Trihalomethanes_2"] = pd.cut(data["Trihalomethanes"],4)""", language="pyhton")

st.image("./Images/visu2.png")
st.image("./Images/1.png")
st.write("Nuestra primera relación entre las variables independientes y la variable objetivo a traves de tablas pivot , nos muestra la cantidad de todas la variables independientes (Chloramines Conductivity Hardness Organic_carbon Solids Sulfate Trihalomethanes Turbidity ph ) por Potabilidad del Agua y por categorización de la variable ph2 a traves de 4 intervalos. Observando así que la cantidad de cada variable varia de forma significativa en cuanto a si es Potable o No Potable.")
st.image("./Images/2.png")
st.write("La relación de las variables independientes y la variable objetivo cuando esta la condición de Hardness2 se observa a traves de la tabla pivot, en ella vemos la probabilidad de la potabilidad del agua cuando se tiene categorización en Hardnees y poniendo a prueba con cada variable independiente.")
st.image("./Images/3.png")
st.write("Para nuestra tercera tabla pivot se analiza la relación entre las variables independientes, la potabilidad y la categorización de la variable Solids 2. Se puede ver que la relación entre No Potable y la independiente Solids es mayor para cada intervalo de Solids 2 frente a los intervalos con Potable.")
st.image("./Images/4.png")
st.write("En la tabla pivot generada a traves de la relación entre las independientes, la dependiente y la variable categorizada Choramines , se observa que en los intervalos (7.333, 9.806] y (9.806, 12.279] de Choramines 2, la potabilidad es en mayor probabilidad para esta.")
st.image("./Images/5.png")
st.write("Nuestra quinta tabla pivot nos permite ver la relación cuando tomamos nuestra independiente categorizada Sulfate con la dependiente Potability y con las demás variables. Vemos que la probabilidad de que el Agua sea No Potable y que tenga Sulfate es mayor que si fuera Potable para cada uno de los intervalos de Sulfate 2.")
st.image("./Images/7.png")
st.write("La relación entre la independiente que muestra la conductividad del agua, contra las demás variables y la objetivo se ve que tiene mayor probabilidad cuando el agua es No Potable para los intervalos (302.785, 424.087] y (545.389, 666.691], en cambio en los intervalos (180.999, 302.785] y (424.087, 545.389] tiene mayor probabilidad cuando el agua es Potable, todo esto respecto a la variable caegorizada Conductivity 2.")
st.image("./Images/8.png")
st.write("Nuestra Septima tabla pivot muestra la relacion entre las independientes, la objetivo y la independiente categorizada Organic Carbon2, se observa que las probabilidades de que el agua No Potable sean mayores que el agua Potable es cuando se relaciona con la Conductivity y Organic Carbon pero en determinados intervalos. Por esta tabla pivot vemos que en determinadas independientes se ve mayor probabilidad cuando es Potable y en otras cuando No.")
st.image("./Images/9.png")
st.write("Para esta penultima tabla pivot podemos ver la relación entre la variable categorizada Trihalomethnes 2, la objetivo Potability y las independientes. Mostrando asi que dentro de Trihalomethanes para los intervalos (14.239, 40.347],(66.35, 92.354] y (92.354, 118.357] es más probable que se tenga mayor cantidad de la independiente en No Potable.")
st.image("./Images/10.png")
st.write("Para nuestra ultima tabla pivot mostrando la relación entre las independientes y la objetivo encontramos que Turbidity 2 es la categorización de si el agua es turbia o no para los intervalos categorizados, a travez de esto podemos concluir que las probabilidades de relación con la variable turbity cuando el agua es potable o no potable osilan entre 2.37 y 5.48.")



st.subheader("visualizacion: ")
st.write(" Para la visulaización de la distribución de los datos realizamos graficos de barras divididos en potable y o potable para cada variable")

st.write("Para el caso de la variable ph, encontramos que independientemente del valor, existen más muestras no potables que potables, encontrandose la mayor cantidad de datos en el intervalo entre ph 6 y ph 8 tanto para potables como para no potables")
st.image("./Images/visu1.png",caption="Poporciones de la variable ph, y de potability en estas")
st.write("Para el caso de la variable solids, la proporción de muestras no potables es mayor en casí todos los intervalos, sin embargo en los intervalos más altos las muestras potables son mayores que las no potables . Por otra parte la mayor cantidad de datos se agrupa entre los valores de 10000 y 30000")

st.image("./Images/visu2.png", caption="Poporciones de la variable solids, y de potability en estas")
st.write("Con la variable Hardness sucede algo similar a lo visto con la variable solids, las muestras no potables son mayores a las potables en casi todos los intervalos, sin embargo en los intervalos más bajos y en los más altos en algunos puntos hay más muestra potables quen no potables. Por otra parte la mayor cantidad de datos se agrupa entre 175 y 225")
st.image("./Images/visu3.png", caption="Poporciones de la variable hardness, y de potability en estas")
st.write("Al igual que con la variable anteriror, en Chloramines las muestras no potables son mayores a las potables en casi todos los intervalos, a excepción de algunos puntos en los intervalos más bajos y en los más altos donde hay más muestra potables que no potables. Adicionalmente entre 6 y 8 se agrupa la mayor cantidad de datos")
st.image("./Images/visu4.png",caption="Poporciones de la variable Chloramiines, y de potability en estas")
st.write("Al igual que con la variable anteriror, en sulfate las muestras no potables son mayores a las potables en casi todos los intervalos, a excepción de algunos puntos en los intervalos más bajos y en los más altos donde hay más muestra potables que no potables, sin embargo estos puntos son mucho más marcados en comparación con las variables anteriores.Por otra parte, aproximadamente entre 325 y 375 se sagrupa la mayor cantidad de datos.")
st.image("./Images/visu5.png",caption="Poporciones de la variable sulfure, y de potability en estas")
st.write("Conductivitysigue la misma tendencia de las variables anteriores de predominio de las muestras no potables en practicamente todos los intervalos a excepciond de pequeños puntos en los intervalos más bajos y más altos , sin embargo, para este caso, los puntos donde resaltan las muestras potables son más pequeños. Por otra parte, aporximadamente entre 325 y 500 se agrupa la mayor cantidad de datos")
st.image("./Images/visu6.png",caption="Poporciones de la variable conductivity, y de potability en estas")
st.write("Para el caso de Organic_Carbon , a excepción de un punto bastante marcado entre 5 y 7.5 donde las muestras potables son mayores a las potables, las muestras no potables son mayores que las potables.Adicoonalmente, entre el 12 y 17.5 aproximandemante se encuentra la mayor cantidad de datos")
st.image("./Images/visu7.png",caption="Poporciones de la variable organic_carbon, y de potability en estas")
st.write("Dentro de la variable Trihalomethanes, resalta un punto entre 60 y 80 en el que el conteo de datos es mayor en comparación con los demas puntos. Adiconalmente dentro de esta variable sigue predominando las muestras no potables.")
st.image("./Images/visu8.png",caption="Poporciones de la variable trihalomethanes, y de potability en estas")
st.write("Por ultimo en Turbidity , las muestras no potables resaltan más que las potables en todos los intervalos. Adiconalmente en 3.5 y 4 se agrupa la mayor cantidad de datos.")
st.image("./Images/visu9.png",caption="Poporciones de la variable turbidity, y de potability en estas")
st.write("Con respecto a las proporciones de la variable objetivo, encontramos que existen más muestras no potables que potables.")
st.image("./Images/propo1.png",caption="Proporcion de la variable potability")
st.subheader("Relacion entre las variables:")
st.write("Para la relación entre variables se realizo un heatmmap y un correlograma dentro de los que se observó es practicamente nula la correlación que existe entre las variables. (colores muy oscuros en el heatmap y puntos sin relación en el correlograma)")
st.image("./Images/rela1.png")
st.image("./Images/pair1.png")

st.write("Para mostrar la relación entre dos distribucciones realizamos boxplots, todos respecto a la variable objeto.")
st.image("./Images/box1.png",caption="Boxlpot de la variable ph" )
st.write("Las dimensiones de la primera caja estan determinadas por el primer y tercer cuartil, para el caso de No Potable (0) Q1 es aproximadamente 6,2 y Q3 es aproximadamente 8, es decir que en nuestro boxplot vemos que el 50 % de ph en No potable esta entre estos dos cuartiles. Para el caso de analizar Potable el 50 % del ph se encuentra entre 6,8 ay 7,7 aproximadamente.Por ultmo a traves del grafico vemos que la mediana se situa en el centro mostrando una simetria y por debajo de la caja se ve la existencia de outliders pero que no afectan nuestro modelo debido a que los que afectan fueron limpiados.")
st.image("./Images/box2.png",caption="Boxlpot de la variable hardness" )
st.write("Las dimensiones para la caja que muestra la distribucción entre Hardness y Potability son para No Potable; Q1 = 175 y Q3=222,5 aproximadamente. Para Potable son de la mismas cantidades aproximadamente. Motivo por el cual se afirma una distribucción 50/50 con la variable objetivo con asimetria. Así mismo se ve la existencia de muy pocos outliders.")
st.image("./Images/box3.png",caption="Boxlpot de la variable solids" )
st.write("Para ver la distribucción entre Solids y Potability la caja muestra que tanto para Potable y No Potable en relación con Solids se presenta una asimetria en la distribucción. Y pocos Outliders en las dos variables en la parte superior.")
st.image("./Images/box4.png",caption="Boxlpot de la variable chloramines" )
st.write("Para la caja de Chloramines y Potability vemos que la distribucción de Potable es de mayor proporción presentando así un Q3 mayor de 8 por lo tanto mayor al Q3 de No Potable. Vemos que para No Potable se encuentran mayores outliders bajo el nivel de 3,8 y para Potable los outliders se encuentran encima del final de la caja quiere decir sobre el nivel de 11 aproximadamente.")
st.image("./Images/box5.png",caption="Boxlpot de la variable sulfate" )
st.write("Para la caja de las variables Sulfate y Potability, observamos que para No potable la distribucción del primer y tercer cuantil es muy pequeña esta entre 325 y 350 aproximadamente en cambio para Potable los cuartiles se encuentran desde 318 y mas de 350 aproximadamente. Para las dos distribucciones se presenta simetria pero para el caso de No potable los outliders permanecen muy concentrados a los extremos.")
st.image("./Images/box6.png",caption="Boxlpot de la variable conductivity" )
st.write("La caja que muestra la distribuccion entre Conductivity y Potability, preseta a simple vista solo un poco de diferencia de dimensiones entre Potable y no Potable. Así mismo se aprecia que cada caja es simetrica y en el caso de No potable - Conductivity se observan pocos outliders por encima del tamaño de la caja.")
st.image("./Images/box7.png",caption="Boxlpot de la variable organic_carbon" )
st.write("En estos ultimos boxplots de distribucciones podemos apreciar que estas son simetricas y tienden a tener un parecido en sus dimensiones mostrando así una distribucción 50/50.Así mismo se mantiene la observación de los outliders en ambas graficas pero en mayor cantidad en No Potable.")
st.image("./Images/box8.png",caption="Boxlpot de la variable trihalomethanes" )
st.write("La penultima box plot nos muestra una simetria casi identica pero la variación de las dimensiones entre Thrihalomethnes-Potable y Truhalomethanes - No potable es de niveles minimos, las mayores diferencias es la cantidad de outliders presentes por encima y encima del tamaño de la caja.")
st.image("./Images/box9.png",caption="Boxlpot de la variable turbidity" )
st.write("El ultimo boxplot nos muestra una simetria casi perfecta entre la distribucción de las variables y una poca cantidad de outliders para las distribucciones. Estas cajas nos pemitieron ver de forma grafica como era el comportamiento de las distribucciones al ponerlas a partir de la objetivo.")
st.subheader("Pruebas de Hipotesis:")
st.write("Se realiza un datasat sin la variable objetivo para realizar la pruab de distribucción normal multivariada")
st.write("Prueba de Hipotesis de normalidad multivariada")
st.write("Ho: El dataset sigue una distribucción normal multivarada")
st.write("Ha: El dataset NO sigue una distribucción normal multivariada.")
st.write("α=0.05")
st.code("""multivariate_normality(data2, alpha = .05 )""",language="python")
st.code("""HZResults(hz=1.1369243176166905, pval=4.509462445228134e-66, normal=False)""",language="python")
st.write("Para la prueba de distribución normal multivariada del dataset sin la variable objetivo, se tiene como resultado un pvalor inferior a 0.05, por lo tanto se asume que el dataset sin la variable objetivo no sigue una distribución normal")
st.write("Para la prueba de distribucción normal, se importa el modulo stats de la libreria scipy y se realiza un normaltest para cada una de las variables, en la cual ya esta incorporada la prueba hipotesis y da como resultado")
st.code("""Columna ph no sigue una distribución normal
Columna Hardness no sigue una distribución normal
Columna Solids no sigue una distribución normal
Columna Chloramines si sigue una distribución normal
Columna Sulfate no sigue una distribución normal
Columna Conductivity no sigue una distribución normal
Columna Organic_carbon si sigue una distribución normal
Columna Trihalomethanes si sigue una distribución normal
Columna Turbidity si sigue una distribución normal""",language="python")
st.write("Se concluye que las variables ph, solids,sulfate,conductivity, turbidity NO siguen una distribucción normal. Mientras que hardness, chloramines,organic carbon, trihalomethanes SI siguen una distribución normal.")

st.write("Se efectua la división del data set para la realización de las diferencias de medias y medianas.")
st.write("Prueba de Hipotesis de diferencia de Medias")
st.write("Ho: Las diferencias de medias es igual")
st.write("Ha: La diferencia de medias es diferente")
st.write("α=0.05")

st.code(""" Para ph, pvalue=0.7606581670556812 """,language="python")
st.code(""" Para Hardness, pvalue=0.38726679870076297 """,language="python")
st.code(""" Para Solids, pvalue=0.5517503508954078""",language="python")
st.code(""" Para Chloramines, pvalue=0.17922819297971626""",language="python")
st.code(""" Para Sulfate, pvalue=0.9231547020388317""",language="python")
st.code(""" Para Conductivity, pvalue=0.8915283492717541""",language="python")
st.code(""" Para Organic_carbon, pvalue=0.31366512921636786""",language="python")
st.code(""" Para Trihalomethanes, pvalue=0.344051884391254""",language="python")
st.code(""" Para Turbidity, pvalue=0.7198537565149352""",language="python")


st.write("A partir de todos los ttest realizados con cada variable, el p-valor de cada uno arroja ser mayor a 0,05 motivo por el cual afirmamos que no hay suficiente evidencia estadistica para rechazar la hipotesis nula por lo tanto se concluye que todas las diferencias de medias de las variables son iguales entre ellas.")

st.code(""" Para ph, pvalue=0.6628768212772176""",language="python")
st.code(""" Para Hardness, pvalue=0.9515843796069338""",language="python")
st.code(""" Para Solids, pvalue=0.9287849061198299""",language="python")
st.code(""" Para Chloraminess, pvalue=0.0817932600039606""",language="python")
st.code(""" Para Sulfate, pvalue=0.8920088296205512""",language="python")
st.code(""" Para Conductivity, pvalue=0.8920088296205512""",language="python")
st.code(""" Para Organic_carbon, pvalue= 0.41726677745854024""",language="python")
st.code(""" Trihalomethanes, pvalue= 0.2243446768114634""",language="python")
st.code(""" Para Turbity, pvalue=0.7531335646890226""",language="python")

st.write("A partir de todos los mediantest realizados con cada variable, el p-valor de cada uno arroja ser mayor a 0,05 motivo por el cual afirmamos que no hay suficiente evidencia estadistica para rechazar la hipotesis nula por lo tanto se concluye que todas las diferencias de medianas de las variables son iguales entre ellas.")

st.subheader("Conclusiones generales:")
st.write("Para este dataset podemos concluir a traves de la visualización de los datos que existe una proporción mayor entre todas las variables y la caracteristica No Potable de nuestra variable objetivo. Así mismo se observo que no existe alguna relación entre las variables independientes. Por ultimo a partir de las pruebas de hipotesis pudimos concluir que las diferencias de medias y de medianas es igual entre cada variable despues de haber realizado una division del dataset a partir de las carcteristicas de la variable objetivo.")
